app_story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.tambahKegiatan, name='tambahKegiatan'),
    path('lihat/', views.lihatKegiatan, name='lihatKegiatan'),
    path('lihat/register/<int:ids>/', views.tambahPeserta, name='tambahPeserta'),
    path('lihat/<int:ids>/', views.hapusPeserta, name='hapusPeserta')
]

firstapp/urls.py
from django.urls import path

from . import views

app_name = 'firstapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('firstapp.urls')),
    path('kegiatan/', include('app_story6.urls'))
]

app_story6/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    Nama_Kegiatan = models.CharField(max_length=50)
    def __str__(self):
        return self.nama

class Peserta(models.Model):
    Nama_Peserta = models.CharField(max_length=50)
    ikutKegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null=True, blank=True)

firstapp/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model):
    mataKuliah = models.CharField(max_length=50)
    dosenPengajar = models.CharField(max_length=25)
    jumlahSKS = models.CharField(max_length=4)
    semesterTahun = models.CharField(max_length=20)
    ruang = models.CharField(max_length=10)
    deskripsi = models.CharField(max_length=100)

    def __str__(self):
        return self.mataKuliah

app_story6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['Nama_Kegiatan']

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['Nama_Peserta']

firstapp/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['mataKuliah', 'dosenPengajar', 'jumlahSKS', 'semesterTahun', 'ruang', 'deskripsi']

app_story6/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm

# Create your views here.

def lihatKegiatan(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    return render(request, 'lihatKegiatan.html', {'kegiatan':kegiatan, 'peserta':peserta})


def tambahKegiatan(request):
    if request.method == "POST":
        form = KegiatanForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('story6:lihatKegiatan')

    else:
        form = KegiatanForm()

    return render(request, 'tambahKegiatan.html', {'form':form})

def tambahPeserta(request, ids):
    if request.method == "POST":
        form = PesertaForm(request.POST)

        if form.is_valid():
            peserta = Peserta(ikutKegiatan=Kegiatan.objects.get(id=ids), Nama_Peserta = form.data['Nama_Peserta'])
            peserta.save()
            return redirect('../../')
    
    else:
        form = PesertaForm()

    return render(request, 'tambahPeserta.html', {'form':form})

def hapusPeserta(request, ids):
    hapus_peserta = get_object_or_404(Peserta, id = ids)

    if request.method == "POST":
        hapus_peserta.delete()
        return redirect('../')

    return render(request, 'hapusPeserta.html', {'hapus_peserta':hapus_peserta})

firstapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
import datetime
from .models import Schedule
from .forms import ScheduleForm



def home(request):
    return render(request,'index.html')

def about(request):
    return render(request, 'profile.html')

app_story6/templates/hapusPeserta.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <h4> Apakah kamu yakin ingin menghapus {{ hapus_peserta.Nama_Peserta }}? </h4>
</div>

<form action="." method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Hapus" />
    <a href="../" class="btn btn-primary">Cancel</a>
</form>
{% endblock %}

app_story6/templates/lihatKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% for x in kegiatan %}
<div class="container">
    <table class="table table-bordered">
        <tr>
            <td class="table-secondary" style="background-color: sandybrown;">{{ x.Nama_Kegiatan }}</td>
        </tr>
        <tr>
            {% for y in peserta %}
            {% if y.ikutKegiatan == x %}
            <tr>
                <td> {{ y.Nama_Peserta }} <a type="button" class="btn btn-outline-danger" href="{% url 'story6:hapusPeserta' y.id %}">Hapus</a></td>
            </tr>
            {% endif %}
            {% endfor %}
        </tr>
    </table>
</div>

<div class="container text-center">
    <a href="register/{{ x.id }}" class="text-white btn btn-primary mx-auto my-2 click">
        Register {{ x.namaKegiatan }}
    </a>
</div>
{% endfor %}

{% endblock %}

app_story6/templates/tambahKegiatan.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block body %}
<form method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    {% csrf_token %}
    {{ form|crispy }}
  
    <h5>* = Wajib Diisi</h5>
    <input class="btn btn-primary" type="submit" value="Save" />
    <a type="button" class="btn btn-primary" href="lihat/"> Lihat Kegiatan</a>
    <a type="button" class="btn btn-success" href="../">Home</a>
  </form>

  
{% endblock %}

app_story6/templates/tambahPeserta.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block body %}
<form method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
  {% csrf_token %}
  {{ form|crispy }}

  <h5>* = Wajib Diisi</h5>
  <input class="btn btn-primary" type="submit" value="Save" />
  <a type="button" class="btn btn-danger" href="../../">Back</a>
</form>

{% endblock %}

firstapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'CSS/main-style.css' %}">
    <link rel="stylesheet" href="assets/bootstrap/css/main-style.css">
    <link rel="stylesheet" href="assets/home/css/style.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Bubblegum+Sans" />
</head>
<body style="background-color: #95d5ff;">
    {% include 'includes/navbar.html' %}
    {% block body %} {% endblock %}

    <br>
    <div class="footer"></div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
    </script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

firstapp/templates/includes/navbar.html
<div class="banner">
  <div style="height: 100%;">
      <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand ml-4 seacolor" href="#">My Note</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto my-3">
                  <li class="nav-item active my-2">
                      <a class="nav-link seacolor" href="./index"><u>Home</u><span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item dropdown my-2">
                      <a class="nav-link dropdown-toggle seacolor" href="#" id="navbarDropdown" role="button"
                          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <u>Content</u>
                      </a>
                      <div class="dropdown-menu bg-seacolor" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="./kegiatan">Kegiatan</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                  </li>
                  <li class="nav-item mr-4 my-2">
                      <a class="nav-link seacolor" href="./profile"><u>About</u><span
                              class="sr-only">(current)</span></a>
                  </li>
              </ul>
          </div>
      </nav>
      <br><br><br><br><br><br><br>
      <div class="container welcome">
          <br>
          <h1>WELCOME TO MY BLOG!!!</h1>
          <br>
      </div>
  </div>
</div>

firstapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<br><br>
<div class="container main">
    <table>
        <tr>
            <td>
                <img src="assets/home/images/deer_art_vector_134088_1280x720.jpg" class="img-fluid">
            </td>
            <td class="gap"></td>
            <td>
                <div class="container">
                    <br><br>
                    <h2 class="sub">Lorem</h2>
                    <hr>
                    <div class="textbox">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        <br>
                        <button type="button" class="btn btn-lg">Read More</button>
                    </div>
                    <br><br>
                </div>
            </td>
        </tr>
    </table>
    <br><br>
    <table>
        <tr>
            <td>
                <div class="container">
                    <br><br>
                    <h2 class="sub">Ipsum</h2>
                    <hr>
                    <div class="textbox">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        <br>
                        <button type="button" class="btn btn-lg">Read More</button>
                    </div>
                    <br><br>
                </div>
            </td>
            <td class="gap"></td>
            <td>
                <img src="assets/home/images/lawn_forest_mountains_144578_1280x720.jpg" class="img-fluid">
            </td>
        </tr>
    </table>
</div>
{% endblock %}

firstapp/templates/profile.html
<html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <title>About</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/bootstrap/css/main-style.css">
    <link rel="stylesheet" href="assets/profile/css/style.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Bubblegum+Sans" />
</head>

<body>
    <div class="banner">
        <div style="height: 40%;">
            <nav class="navbar navbar-expand-lg">
                <a class="navbar-brand ml-4 seacolor" href="home.html">My Note</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto my-3">
                        <li class="nav-item my-2">
                            <a class="nav-link seacolor" href="home.html"><u>Home</u><span
                                    class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown my-2">
                            <a class="nav-link dropdown-toggle seacolor" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <u>Content</u>
                            </a>
                            <div class="dropdown-menu bg-seacolor" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Kegiatan</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item active mr-4 my-2">
                            <a class="nav-link seacolor" href="#"><u>About</u><span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <img class="pp" src="assets/profile/images/me.jpg">
        <br>
    </div>

    <br>
    <div class="container">
        <br>
        <h2 class="name">Muhammad Daffa Syammary</h2>
        <h3 class="npmangkatan">1906399146<br>2019</h3>
        <br>
    </div>

    <br>
    <div class="container">
        <br>
        <h2 class="sub">About Me</h2>
        <hr>
        <div class="textbox">
            <p>A student who has experienced in organizing, human development, and project management.
                He always think critically, has the ambition to compete with others,
                and excited to learn a new things.</p>
        </div>
        <br>
    </div>

    <br>
    <div class="container">
        <br>
        <h2 class="sub">Education</h2>
        <hr>
        <div class="textbox">
            <table>
                <tr>
                    <td>
                        <div class="conbox"><img src="assets/profile/images/Makara_UI.png" class="icon"></div>
                    </td>
                    <td>
                        <div class="edu">Universitas Indonesia - Information System</div>
                    </td>
                    <td>
                        <div class="year">2019 - present</div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="2">
                        <ul>
                            <li>Vice Project Officer Pemilihan Raya IKM Fasilkom UI 2020</li>
                            <li>Human Research and Development of Stage Division Compfest 12</li>
                            <li>Finalist of Technofair 7 Business Plan Competition</li>
                            <li>Finalist of Diponegoro Entrepreneur Festival 2020 Business Plan Competition</li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="conbox"><img src="assets/profile/images/Sman_39_jakarta-removebg-preview.png"
                                class="icon"></div>
                    </td>
                    <td>
                        <div class="edu">SMAN 39 Jakarta</div>
                    </td>
                    <td>
                        <div class="year">2016 - 2019</div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="2">
                        <ul>
                            <li>Leader of Majelis Perwakilan Kelas SMAN 39 Jakarta</li>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
        <br>
    </div>

    <br>
    <div class="container">
        <br>
        <h2 class="sub">Hobby</h2>
        <hr>
        <div class="textbox">
            <table>
                <tr>
                    <td>
                        <div class="conbox"><img src="assets/profile/images/book-removebg-preview.png" class="icon">
                        </div>
                    </td>
                    <td>
                        <div>Reading Novel</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="conbox"><img src="assets/profile/images/movies-removebg-preview.png" class="icon">
                        </div>
                    </td>
                    <td>
                        <div>Watching Movies</div>
                    </td>
                </tr>
            </table>
        </div>
        <br>
    </div>

    <br>
    <div class="container">
        <br>
        <h2 class="sub">Social Media</h2>
        <hr>
        <div class="textbox">
            <table>
                <tr>
                    <td>
                        <div class="conbox"><img src="assets/profile/images/gmail-removebg-preview.png" class="icon">
                        </div>
                    </td>
                    <td>
                        <div><a class="linkk" href="mailto:daffasyammary27@gmail.com">daffasyammary27@gmail.com</a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="conbox"><img src="assets/profile/images/line-removebg-preview.png" class="icon">
                        </div>
                    </td>
                    <td>
                        <div><a class="linkk" href="https://line.me/ti/p/6mBxUZ88LF">daffasyammary</a></div>
                    </td>
                </tr>
            </table>
        </div>
        <br>
    </div>

    <br>
    <div class="footer"></div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
    </script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>